[theme]
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = false

[ui]
hideTopBar = true
hideSidebarNav = true

[client]
showSidebarNavigation = false

[layout]
wideMode = true
